name: Deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: recipe-api
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/geekmonstar/${{ env.IMAGE_NAME }}
          image_name: ${{ env.REGISTRY }}/geekmonstar/${{ env.IMAGE_NAME }}
          tags: ${{ steps.get-latest-tag.outputs.tags }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          build_args: |
            DATABASE_URL: ${{ env.DATABASE_URL }}
      
      - name: Deploy the new image
        uses: appleboy/ssh-action@master  
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ env.REGISTRY }}/geekmonstar/${{ env.IMAGE_NAME }}:${{ steps.metadata.outputs.tags }}
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true
            docker run -d --restart=always --name ${{ env.IMAGE_NAME }} -p ${{ secrets.VPS_PORT }}:3000 -e DATABASE_URL=$DATABASE_URL ${{ env.REGISTRY }}/geekmonstar/${{ env.IMAGE_NAME }}:${{ steps.metadata.outputs.tags }}
