name: Deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kitchin-backend
  IMAGE_PATH: ghcr.io/geekmonstar/kitchin-backend
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PATH }}:latest
          build-args: |
            DATABASE_URL=${{ env.DATABASE_URL }}

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u geekmonstar --password-stdin
            docker pull ${{ env.IMAGE_PATH }}:latest
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true
            docker run -d \
              --restart=always \
              --name ${{ env.IMAGE_NAME }} \
              -p ${{ secrets.VPS_PORT }}:3000 \
              -e DATABASE_URL="${{ env.DATABASE_URL }}" \
              ${{ env.IMAGE_PATH }}:latest
